name: Docker Image Push

env:
  APP_VERSION: 0.3.0
  WS_VERSION: 1.0.0
  DB_VERSION: 1.0.0

on:
  push:
    branches: [ "releases/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Docker Compose
      uses: docker/setup-compose-action@v1.2.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Build Docker images
      run: docker compose build --profile prod
              --build-arg NEXT_PUBLIC_URL="${{ vars.URL }}" 
              --build-arg NEXT_PUBLIC_VAPID_PUBLIC_KEY="${{ vars.VAPID_PUBLIC }}"
              --build-arg NEXT_PUBLIC_NINJA_API_KEY="${{ secrets.NINJA_API }}"

    - name: Publish Docker latest images
      run: docker compose push --profile prod

    - name: Version tag images.
      run: docker tag risheitm/c01-go-pulse-app risheitm/c01-go-pulse-app:${{ env.APP_VERSION }};
           docker tag risheitm/c01-go-pulse-websocket risheitm/c01-go-pulse-websocket:${{ env.WS_VERSION }};
           docker tag risheitm/c01-go-pulse-database risheitm/c01-go-pulse-database:${{ env.DB_VERSION }}
    
    - name: Push versioned images.
      run: docker push risheitm/c01-go-pulse-app; 
           docker push risheitm/c01-go-pulse-websocket; 
           docker push risheitm/c01-go-pulse-database