name: Docker Image Push

on:
  push:
    branches: [ "releases/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Docker Compose
      uses: docker/setup-compose-action@v1.2.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Build Docker images
      run: docker compose build --profile prod
              --build-arg NEXT_PUBLIC_URL="${{ vars.URL }}" 
              --build-arg NEXT_PUBLIC_VAPID_PUBLIC_KEY="${{ vars.VAPID_PUBLIC }}"
              --build-arg NEXT_PUBLIC_NINJA_API_KEY="${{ secrets.NINJA_API }}"
    - name: Publish Docker images
      run: docker compose push --profile prod