name: Docker Image Push

env:
  APP_VERSION: 0.3.1
  WS_VERSION: 1.0.0
  DB_VERSION: 1.0.0

on:
  push:
    branches: [ "release/**", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Docker Compose
      uses: docker/setup-compose-action@v1.2.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Build Docker images
      run: docker compose --profile prod build
              --build-arg NEXT_PUBLIC_VAPID_PUBLIC_KEY="${{ vars.VAPID_PUBLIC }}"
              --build-arg NEXT_PUBLIC_NINJA_API_KEY="${{ secrets.NINJA_API }}"

    - name: Publish Docker latest images
      run: |
        touch .env;
        docker compose --profile prod push 

    - name: Version tag images.
      run: docker tag risheitm/c01-go-pulse-app risheitm/c01-go-pulse-app:${{ env.APP_VERSION }};
           docker tag risheitm/c01-go-pulse-websocket risheitm/c01-go-pulse-websocket:${{ env.WS_VERSION }};
           docker tag risheitm/c01-go-pulse-database risheitm/c01-go-pulse-database:${{ env.DB_VERSION }}
    
    - name: Push versioned images.
      run: docker push risheitm/c01-go-pulse-app:${{ env.APP_VERSION }}; 
           docker push risheitm/c01-go-pulse-websocket:${{ env.WS_VERSION }};
           docker push risheitm/c01-go-pulse-database:${{ env.DB_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Connect to EC2 instance and deploy app
      env:
        PRIVATE_KEY: ${{ secrets.AWS_EC2_KEY }}
      run: |
         echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem;
         ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.AWS_EC2_USER }}@ec2-3-19-141-1.us-east-2.compute.amazonaws.com '
            docker-compose --profile prod down &&
            docker-compose --profile prod pull &&
            docker-compose --profile prod up -d
            '